languages:

  - English
  - Traditional Chinese


disease_priority:

  - Endometrial Cancer
  - Colorectal Cancer
  - Rectal Cancer
  - Colon Cancer
  - Head and Neck Cancer
  - Ovarian Cancer
  - Gastrointestinal Stromal Tumor
  - Lung Cancer


companies:

  - GSK
  - Nuvalent


assets:

  - Dostarlimab
  - Jemperli

  - Mo-Rez
  - Mocertatug Rezetecan
  - GSK5733584

  - Ris-Rez
  - Risvutatug Rezetecan
  - GSK5764227

  - Velzatinib
  - Zidesamtinib
  - IDRX-42
  - Neladalkib


trials:

  - RUBY
  - JADE
  - DUO-E
  - NRG-GY018
  - BEHOLD
  - ARTEMIS
  - DOMENICA
  - StrateGIST
  - EMBOLD
  - ARTEMIS
